language: r
sudo: false
cache: packages
warnings_are_errors: false
after_success:
  - Rscript -e 'covr::coveralls()'
  - mkdir deploy
  - cp "${PKG_FILE_NAME}" deploy/latest.tar.gz
notifications:
  email:
    recipients:
    - graeme.blair@ucla.edu
    - alex.coppock@yale.edu
    on_success: change
    on_failure: change
