language: r
sudo: false
cache: packages
warnings_are_errors: false
after_success:
  - Rscript -e 'covr::coveralls()'
  - mkdir deploy
  - cp "${PKG_FILE_NAME}" deploy/latest.tar.gz
deploy:
  provider: s3
  bucket: experimentr.org-jekyll
  region: us-east-1
  local-dir: deploy
  skip_cleanup: true
  access_key_id: "$AWS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
notifications:
  email:
    recipients:
    - graeme.blair@ucla.edu
    - alex.coppock@yale.edu
    on_success: change
    on_failure: change
env:
  global:
  - secure: GTsToYIcGZEknVFQw4JM5e6A8AFEwKBmUGug48TOqFrfPDlW2jg0fYqHVnm3n0cHrtidD0P5ru97zN+RcMJTvMW6D3dmwvRKC3qWdGzpl7MJXQkJqjRuJfh2XmTia3AcrV93jo+Vpq+mnHBlpEtJY2e/LwsotMCwJAkIviq1JmRU+3X1IYkj3j7/7IkZdNXcHfA8bMKoeV130+PKCugt0DOxzEMF6q8LvVxKNMReg23GDohT0sYu7Cudpr4nlokgfMpmK0qSl7jZcbb90lFLTR6DsNzm6sJPW8+uc01HBZM/HXMnT6TsDR5XfqK0HwWjCyYEHPg5wh3KVEOEDoZNkld3YmRwwJwux7z4JfTvpz6Ssm/rhb7jui6e+68sE3eikcChURqgRirS8/7CeWUcqIUFhF1slT0yBrNMazgAyDp+ZZFqVqIpvGF0Bra66349SINxl9iZuaE8V5t77mHVhBfB9POv22/XnFPaQ0lOsJH7GzC0zScA4OcZKsF2iyHt04vMTPnlyybmea7FoipxbWOOjR7UaZKkf7gO4zzYor2iwVsybdWVHgSo4VVPCzfmu3d5WwLuo44HKLVvr8XarmE2YqyPsJifHVRRkTkcuKFHeL6MPgxSw6cwyzcKmdZnMA8xZcHQ4gHoPN52mnh1h6zvsjiddqL7j3RZ6tR60YA=
  - secure: rJzxzt8ujDgbwvaZOHqcUcV0n2pDJbwYlOTt5O5jNnb07dT64wt9hKkDhcJ4O0fbybpwOUF3Fn3LckEZfTKEnOUFzUSPl3PMvE+SPbUdfGw4eM9OdSFX0AFkOPkOofGpS1hqKT33ZEt44AYOAjaRjDF5JBCPSNDPjwRzxqyW9Ljz/GLX1aePsjY//AZHNtWAGiZzJ0AsB42stqfVy1Ctdu3xGbnBjkgrAqPebPPmWKB/+NfR4jBIAPu5nf6FkcCyftd3h8+xrHMX9RaZbHOYGm+5LDtbgllaFYUaCR15dY8f4/NPwOy4fKEfDduWSGV59OXY9EqHxSr29fN5NMfmQENNW8da1DkoftbN/IxfRc69Yv2qgFG22XwpnRr6zj8SCs5NxmCwM/7TFRQJdkzd9osSmMJXRQ1vrDVyjxVxJfrSHQpDKLg7g2AvL+RliYpjtFSnsxrxiP8t8rhSffkF0B5zSToFlt0mRUxBlbdMxt7zCuaMtCOg6h3wQjzShT6wP41RLUGQHSXiStnvsI/6ADo3vuIXgJtIYc/uPeXCi61DWl1c9yCCYbf0twq/YZcTv/3pIoaKP7Hs7JOYILrYK5MOI4LViloZg7Nzorh+mQR/EaxgH/zgzLxc+QeihGiv0MIiufieK1XF5FFEtopmdAWuGkyv8SwbYlJjKeduVLY=
  - secure: Pp/Y3QROpbFuXqrmUTHDVqAIK6ukKT5MgMcx9PEsib89avJFX9RdheKf0uNU2hLBtUK8WeffEGuu5ib8iRif9gtY0svlyL24CpFiZexJHYghuxAcXnywM3p+WpUdE/n3zuQ6nN41efaE666d1LhjQF5YHhlzjAsuYeOwSYNvLqpWiaSY7H/gpBn4vQUd8yV2MOYrm46ImWm+TFcCYYf4PE2u9RRzHNeAtnoQ2WXnv47d4iUrqLUfoK530SJq5g1ySih6jg6x8klO2pZlKMGMjnCgzZrVl9X0lZ/F4aw0/8lSflCgLWUI0258rHmJ3EL+5x4P5mcxltudDSQ5SpNNv51CBJVOn+cOCk+mKFH693GJYhmi4BEv6ADftmR5PM2ovFSiNU557KBxm4BIZhFMAtmcIP/lXvarNaMpDsbd47VBnOTOmEm/+4CFdTE2CHIxl1FiAQYlU0CL/gd6NVCu6DE27oRyPN4icwMf7T7J+j4XQQMkYRQUy4xfC06ATcGdQeUxWQcgecqoor2PonFB5Lyf5OMXqM/TCukuPcWUxC7pFwHgfS2pVf3BgruULlp/PAvKF2CA58FNktwkece/PViLlahNlMdih4aV9fpWkBOj490CCTbDSmX8YxmobcVq5DfDtH2T0JrT1A9P4ueFdXnM0RTX5EpR26DcNZ+pFNw=
