language: r
r:
- release
sudo: false
cache: packages
warnings_are_errors: false
os:
- linux
- osx
env:
  global:
  - OS=$(uname -s)
  matrix:
    secure: uD22NS6NdLhJjqF1Wy36YkhBENOAffakReMB5kXFk/a6uf3Uf9vEq/mKV0d7xe/vIYi2MTTA30IBK2X9/vonUho5TygdOVCzuqMkcy5NFq5/MTpp89WalXBlR80ogV/51mArM2VzYJfkIQhbhQiTPfxoOQB1THN61vPLDDnfKwvzIcI18VRHlmvV4RthLy5cFmMYOQHU3k/hNOVObrYblYKW2XmLVQqi2sU6CWintr0o7pIvl9nG52D++N/wesbIa7L0QaU+G6T/2jgPV3H4Tn2S3iW7+fOUlcSqCLVj8JqQfLp51Uze38PseyUgp+ntjNyh2U5ZF0g1QAStf42yB/3I+kKuhwAd1Q3dwLRb19frKXjM+iCdYoEeyntTchhgwDiT7EYiVFrfqJeeMJkC8xluN9F4WoBYuL8pxkJ0qiN7xlNnjDNwM/q034w6SHwxO4+KFpSuXYexg5kvtIKKSDxpbhJ4reKumoZ+lOXZBLKPE7aiCLKoovNbUx8cEmBp8XOpQlw/hdaLzmwllCWVu9o5FMLbivjXB94/MCvZry50JYCU3PT8O0MaAMZIb7Copr4zWF3B7yuGIUunehiFRvITts6o+Cs8gY/DrDPs0DLYO7KuYOcNP0uYGWVXqUhupcvLt7v0bUnNflagranBdwlnGgIOJPL1bhCUl4gZsfo=
r_github_packages:
- jimhester/covr
- graemeblair/drat
r_packages:
- git2r
after_success:
- Rscript -e 'covr::coveralls()'
- test $TRAVIS_OS_NAME == "osx" && Rscript -e "devtools::build(binary = TRUE, args
  = c('--preclean'))"
- test $TRAVIS_OS_NAME == "linux" && Rscript -e "devtools::build()"
- test $TRAVIS_REPO_SLUG == "DeclareDesign/DeclareDesign" && test $TRAVIS_PULL_REQUEST
  == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
notifications:
  email:
    recipients:
    - graeme.blair@ucla.edu
    - alex.coppock@yale.edu
    on_success: change
    on_failure: change
