# DO NOT CHANGE the "init" and "install" sections below

# Change SilentlyContinue to Stop for production (Graeme)
# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "SilentlyContinue"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here
environment:
  GH_TOKEN:
    secure: 7dAyrUdSY265j0EnmQSBiOa6AtQaTNF25C6v0ntJEejJMMPMB2uOx1yYl/3ro0d9

  matrix:
  - R_VERSION: release

  - R_VERSION: oldrel
    RTOOLS_VERSION: 33

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_success:
  - if NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER (if %APPVEYOR_REPO_BRANCH% == master ( travis-tool.sh install_github DeclareDesign/DDtools && Rscript -e "DDtools::update_drat()" ) )

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
