---
title: "Design Library"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Design Library}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Our design library characterizes designs informally and in code using the $<M,I,D,A>$ framework (for more on this framework, see [our paper](http://declaredesign.org/paper.pdf)):

- A **model**, *M*, of how the world works. The model specifies the moving parts --- the variables --- and how these are causally related to each other. In this sense the model provides the context of a study, but also a speculation about the world.    

- An **inquiry**, *I*, about the distribution of variables, perhaps given interventions on some variables.  In many applications *I* might be thought of as the "estimand." Some inquiries are statements about the values of variables, others about the causal relations between variables. In all cases however the inquiry should be answerable given the model.   

- A **data strategy**, *D*, generates data on variables.  Note that implicitly the data strategy includes case selection, or sampling decisions, but it also represents interventions such as assignment of treatments or measurement strategies. A model *M* tells you what sort of data you might observe if you employ data strategy *D*.  

- An **answer strategy**, *A*, that uses data to generate an answer.  

---

## Designs

--------------------------- -----------------------------------------------------------------------------------------------------------------------
Goal                        Strategy      Design                                                                  Download 
--------------------------- ------------- ----------------------------------------------------------------------- --------------------------------
Causal inference            Experimental  [Two-Arm Experiment](../articles/two_arm.html)                          <a class="btn btn-default" href="http://declaredesign.org/articles/two_arm.R"><i class="fa fa-code" title = "Download code for design"></i></a> <a class="btn btn-default" href="http://declaredesign.org/articles/two_arm_template.RDS"><i class="fa fa-clipboard" title = "Download template for design"></i></a>
                                                                                                                   
Causal inference            Experimental  [Two-Way Factorial Experiment](../articles/two_way_factorial.html)      <a class="btn btn-default" href="http://declaredesign.org/articles/two_way_factorial.R"><i class="fa fa-code" title = "Download code for design"></i></a> <a class="btn btn-default" href="http://declaredesign.org/articles/two_way_factorial_template.RDS"><i class="fa fa-clipboard" title = "Download template for design"></i></a>
                                                         
Causal inference            Observational [Regression Discontinuity](../articles/regression_discontinuity.html)   <a class="btn btn-default" href="http://declaredesign.org/articles/regression_discontinuity.R"><i class="fa fa-code" title = "Download code for design"></i></a> <a class="btn btn-default" href="http://declaredesign.org/articles/regression_discontinuity_template.RDS"><i class="fa fa-clipboard" title = "Download template for design"></i></a>
--------------------------------------------------------------------------------------------------------------------------------------------------


## Using the design library

There are three main ways you can learn about the designs in the library:
  
  1. Read through the vignettes (click the links under "Design" in the table above).
  2. If you have [installed DeclareDesign](http://declaredesign.org/#installing-declaredesign), download the code for the design or the design template and create your own, modified versions of the designs. Diagnose them on your own computer using `diagnose_design()` (click on the buttons under "Download" in the table above).
  3. Import designs from the library into the [Design Inspector <i class="fa fa-area-chart" title = "Go to the design inspector" fa-2x></i>]("http://shiny.declaredesign.org:8000/") and investigate their properties. You can also download the code for the designs, modify it, and upload the design back into the inspector again. 


