---
title: "Two-Way Factorial Experiment"
output: rmarkdown::html_vignette
bibliography: bib.bib
vignette: >
  %\VignetteIndexEntry{Two-Way Factorial Experiment}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r MIDA, echo = FALSE,include = FALSE}
library(DeclareDesign)

two_way_factorial_template <- function(N=c(30, 100, 500, 1000),
                             beta_A=c(1, -1, 0),
                             beta_B=c(-1, 0, 1),
                             gamma_AB=c(.5, -1, -.5, 0, 1))
{
  N <- as.numeric(N[1])
  beta_A <- as.numeric(beta_A[1])
  beta_B <- as.numeric(beta_B[1])
  gamma_AB <- as.numeric(gamma_AB[1])



  my_population <- declare_population(N = N, noise = rnorm(N))

  my_potential_outcomes <- declare_potential_outcomes(Y_Z_T1 = noise,
                                                      Y_Z_T2 = noise + beta_A,
                                                      Y_Z_T3 = noise + beta_B,
                                                      Y_Z_T4 = noise + (beta_A + beta_B + gamma_AB)
                                                      )

  my_assignment <- declare_assignment(num_arms = 4)

  # Note need to return scalar below, otherwise it is bad. DO NOT INCLUDE gamma_AB in potential_outcomes call above, it will make a new column. --NJF 11/15
  my_estimand <- declare_estimand(interaction = gamma_AB, label = "interaction")

  my_estimator <- declare_estimator(Y ~ Z1 + Z2 + Z1*Z2,
                                    model = lm_robust,
                                    coefficient_name = "Z1:Z2", estimand = my_estimand)

  my_design <-
    declare_design(
      my_population,
      my_potential_outcomes,
      my_estimand,
      my_assignment,
      dplyr::mutate(Z1 = as.numeric(Z %in% c("T2", "T4")),
                    Z2 = as.numeric(Z %in% c("T3", "T4"))),
      reveal_outcomes,
      my_estimator
    )

  my_design
}
attr(two_way_factorial_template, "tips") <- c(
  "N"="Size of population",
  "beta_A"="Main effect of A",
  "beta_B"="Main effect of B",
  "gamma_AB"="Interaction effect of A and B"
)

# saveRDS(two_way_template, "~/two_way.RDS")

```



### Design Declaration

- **M**odel: 
    

- **I**nquiry: 
    

- **D**ata strategy: 
    

- **A**nswer strategy: 
    


```{r}
# Model ------------------------------------------------------------------------

# Inquiry ----------------------------------------------------------------------

# Data Strategy ----------------------------------------------------------------

# Answer Strategy --------------------------------------------------------------

# Design -----------------------------------------------------------------------
```


### Takeaways 

With the design declared we can run a diagnosis from Monte Carlo simulations of the design:

```{r,eval = FALSE, echo = FALSE}
diagnosis <- diagnose_design(two_way_factorial_template(), sims = 10000, bootstrap_sims = 1000)
saveRDS(diagnosis,"two_way_factorial_diagnosis.RDS")
```


```{r,eval = FALSE, echo = TRUE}
diagnosis <- diagnose_design(two_way_factorial_template(), sims = 10000, bootstrap_sims = 1000)
```

```{r,echo = FALSE}
if(file.exists("two_way_factorial_diagnosis.RDS")) diagnosis <- readRDS("two_way_factorial_diagnosis.RDS")
if(exists("diagnosis")) {
  diagnosands <- get_diagnosands(diagnosis)
  # diagnosis_table <- diagnosands[,c("mean_estimate","mean_estimand","bias","se(bias)","power","se(power)","coverage","se(coverage)")]
  # names(diagnosis_table) <- c("Mean Estimate", "Mean Estimand", "Bias", "SE(Bias)", "Power", "SE(Power)", "Coverage", "SE(Coverage)")
  # knitr::kable(diagnosis_table,digits = 3)
  # 
  # mean_estimate <- round(diagnosands[1,"mean_estimate"],3)
  # mean_estimand <- round(diagnosands[1,"mean_estimand"],3)
  # bias <- round(diagnosands[1,"bias"],3)
  # power <- round(diagnosands[1,"power"],2)*100
  # coverage <- round(diagnosands[1,"coverage"],2)*100
}
```

TODO

### Further Reading

TODO

### Exercises

TODO



## References {-}





























