
#' Declare design via the `+` operator
#' 
#' @param lhs An object of class \code{dd} or \code{design}.
#' @param rhs An object of class \code{dd} or \code{design}.
#' 
#' @return A \code{design} object. 
#' 
#' @examples 
#' 
#' pop <- declare_population(N = 100)
#' smp <- declare_sampling(n = 50)
#' assgn <- declare_assignment(m = 25)
#' 
#' my_design <- pop + smp + assgn
#' 
#' @importFrom rlang enexpr expr_deparse
#' 
#' @export
`+.d_par` <- function(lhs, rhs){
  
  # two cases
  # 1. lhs is a step
  # 2. lhs is a design
  
  # browser()
  
  if (!inherits(rhs, "d_par")) {
    stop("The right hand side does not appear to be a dd object. Can you wrap the step with `tidy_step()`?", call. = FALSE)
  }
  
  
  if (inherits(lhs, "design")) {
    
    # browser()
    auto_steps <- sapply(lhs, function(x) { lbl <- attr(x, "label"); !is.null(lbl) && grepl("Autogenerated by ", lbl) })
    if (any(auto_steps)) {
      lhs <- lhs[!auto_steps]
    }
    
    ret <- append(lhs, rhs)
    
    # browser()
    
    names(ret)[length(ret)] <- expr_deparse(enexpr(rhs))
    
    ret <- do.call(declare_design_internal, ret)
    
  } else {
    
    ret <- append(lhs, rhs) 
    
    names(ret) <- c(expr_deparse(enexpr(lhs)), expr_deparse(enexpr(rhs)))
    
    ret <- do.call(declare_design_internal, ret)
    
  }
  
  ret
  
}

`%i%` <- intersect

`%||%` <- function(e1, e2) if(is.null(e1)) e2 else e1
