#' print.design_comparison
#' Print function for design comparison.
#' @param design_comparison A comparison generated by compare_designs.
#' @param display c("highlights", "all", "none"), where highlights is the default.
#' @param Rmd_file_prefix Optional. If provided, creates Rmd template based on display type. E.g., "my_comparison". 
#' @method print design_comparison
#' @export
print.design_comparison <- function(design_comparison, 
                                    display = c("highlights", "all", "none"),
                                    Rmd_file_prefix = NULL){
  
  if(is.null(Rmd_file_prefix)){
    
    print_dc(dc = design_comparison, 
             display = match.arg(display, c("highlights", "all", "none")))
    
  }else{
    
    print_dc(dc = design_comparison, 
             display = match.arg(display, c("highlights", "all", "none")), 
             file_name = paste0(Rmd_file_prefix, ".Rmd"))
  }
  
}

# internal version of print.design_copy
print_dc <- function(dc, display, file_name = NULL, to_Rmd = FALSE){
  
  Rmd <- !is.null(file_name)
  
  if(Rmd){
    
    header <- c("---", 
                "title: DeclareDesign Comparisons", 
                "output: html_document", 
                "---")
    body <- capture.output(print_dc(dc, display, to_Rmd = TRUE))
    writeLines(c(header, body), file_name)
    
  }else{
    
    if(display != "none"){
      
      md("Overview of", dc$N_designs, "designs", N_hashtags = 1) # top of outline
      
      # md() is markdown-friendly wrapper for cat()
      
      if(difference(dc$steps_per_design)){
        
        md("Designs included in comparison: ", 
           paste(dc$design_names, collapse = ", "), ".", sep="")
        print_md(t(dc$steps_per_design), to_Rmd = to_Rmd)
        
      }else{
        
        md("Designs included in comparison: ", paste(dc$design_names, collapse = ", "),
           ".\nEach design has ", unique(dc$steps_per_design), " steps. ", 
           sep="", trail_breaks = 1)
        
      }
      md("Design steps compared: ", paste(colnames(dc$similarity), collapse = ", "), 
         ".\nComparisons below are made to ", dc$reference_design, ".", 
         lead_breaks = 0, sep="")
      
    } 
    
    if(display == "all") {
      
      md("Tests for Equality", N_hashtags = 2)
      print_md(dc$equality_comparisons, to_Rmd = to_Rmd)
      
      md("Code Overview", N_hashtags = 2)
      
      for(i in 1:ncol(dc$overview)){
        md(colnames(dc$overview)[i], N_hashtags = 3, trail_breaks = 1)
        if(to_Rmd) cat("```\n")
        md(paste("\n\n", dc$design_names, ": ", dc$overview[,i], sep=""), 
           lead_breaks = 0)
        if(to_Rmd) cat("```\n")
      }
      
    }else{
      if(display == "highlights"){
        
        md("Tests for Equality", N_hashtags = 2)
        print_md(dc$equality_comparisons[-which(rownames(dc$equality_comparisons) == dc$reference_design), 
                                      colMeans(dc$equality_comparisons) < 1], 
                 to_Rmd = to_Rmd)
        
        if(length(dc$highlights) == 0){
          md("No differences between designs to highlight.")
        }else{
          md("Design Steps which differ from that of", dc$reference_design, N_hashtags = 2)
          if(mean(dc$identical_steps) != 1) {
            if(to_Rmd) cat("```\n")
            for(i in 1:length(dc$highlights))
              md(dc$highlights[i], trail_breaks = 1, lead_breaks = 0)
            if(to_Rmd) cat("```\n")
          }
          if(length(dc$code_differences)){
            md("Differences detected in code stored as design attributes", N_hashtags = 2)
            print_md(dc$code_differences, to_Rmd = to_Rmd)
          }
        }
      }
    }
  }
}

# convenient markdown-style outlining of output
md <- function(a, b = NULL, c = NULL, d = NULL, e = NULL, f = NULL, g = NULL,
                    N_hashtags = 0, lead_breaks = 1, trail_breaks = 2, ...){

  cat(rep("\n", lead_breaks))
  cat(paste(rep("#", N_hashtags), collapse = ""), 
      a, b, c, d, e, f, g,
      rep("\n", trail_breaks), ...)
}

print_md <- function(..., to_Rmd=FALSE){
  
  if(to_Rmd) cat("```r\n")
  print(...)
  if(to_Rmd) cat("```\n")
  
}
