#' print.design_comparison
#' Print function for design comparison.
#' @param design_comparison A comparison generated by compare_designs.
#' @param display c("highlights", "all", "none"), where highlights is the default. 
#' @method print design_comparison
#' @export
print.design_comparison <- function(design_comparison, 
                                    display = c("highlights", "all", "none")){
  
  display <- match.arg(display, c("highlights", "all", "none"))
  dc <- design_comparison 
  
  if(display != "none"){
    
    md("Overview of", dc$N_designs, "designs", N_hashtags = 1) # top of outline
    
    # md() is markdown-friendly wrapper for cat()
    
    if(difference(dc$steps_per_design)){
      
      md("Designs included in comparison: ", 
         paste(dc$design_names, collapse = ", "), ".", sep="")
      print(t(dc$steps_per_design))
      
    }else{
      md("Designs included in comparison: ", paste(dc$design_names, collapse = ", "),
         ". Each design has ", unique(dc$steps_per_design), " steps. ", 
         sep="", trail_breaks = 0)
      
    }
    md("Design steps compared: ", paste(colnames(dc$similarity), collapse = ", "), 
       ". Comparisons below are made to ", dc$reference_design, ".", 
       lead_breaks = 0, sep="")
    
  } 
  
  if(display == "all") {
    
    md("Tests for Equality", N_hashtags = 2)
    print(dc$equality_comparisons)

    md("Code Overview", N_hashtags = 2)
    
    for(i in 1:ncol(dc$overview)){
      md(colnames(dc$overview)[i], N_hashtags = 3, trail_breaks = 1)
      md(paste("\n\n", dc$design_names, ": ", dc$overview[,i], sep=""), 
         lead_breaks = 0)
    }
    
  }else{
    if(display == "highlights"){
      
      md("Tests for Equality", N_hashtags = 2)
      print(dc$equality_comparisons[-which(rownames(dc$equality_comparisons) == dc$reference_design), 
                                    colMeans(dc$equality_comparisons) < 1])

      if(length(dc$highlights) == 0){
        md("No differences between designs to highlight.")
      }else{
        md("Design Steps which differ from that of", dc$reference_design, N_hashtags = 2)
        if(mean(dc$identical_steps) != 1) {
#          md("Differences detected from", dc$reference_design, trail_breaks = 1)
          for(i in 1:length(dc$highlights))
            md(dc$highlights[i], trail_breaks = 1, lead_breaks = 0)
        }
      }
    }
  }
  md("Differences detected in code stored as design attributes", N_hashtags = 2)
  print(dc$code_differences)
  
}

# convenient markdown-style outlining of output
md <- function(a, b = NULL, c = NULL, d = NULL, e = NULL, f = NULL, g = NULL,
                    N_hashtags = 0, lead_breaks = 1, trail_breaks = 2, ...){

  cat(rep("\n", lead_breaks),
      paste(rep("#", N_hashtags), collapse = ""), 
      a, b, c, d, e, f, g,
      rep("\n", trail_breaks), ...)
}
